<a href="https://colab.research.google.com/github/ty-bennett/google_colab_linear_alg/blob/main/Math344L_Assignment1_Ty_Bennett.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Problem 1. Vectors and NumPy

import numpy as np

In [8]:
u = np.array([2,-1,3])
v = np.array([4,2,-2])

In [15]:
# b. Create u and v as NumPy arrays and verify answers
# 1. u+v, 3u-2v, u dot v

In [16]:
# U + V
print(u+v)

[6 1 1]


In [17]:
# 3u - 2v
print(3*u - 2*v)

[-2 -7 13]


In [18]:
# u dot v
print(np.dot(u,v))

0


In [20]:
# Problem 2. Matrix Multiplication
# Let A=(1 2 and B = (2 0
#       -1 3)         4 1)
#
# b. Compute AB and BA and verify answers in Python

In [22]:
a = np.array([[1, 2], [-1, 3]])
b = np.array([[2, 0], [4, 1]])


In [24]:
print(a@b)
print(b@a)

[[10  2]
 [10  3]]
[[ 2  4]
 [ 3 11]]


In [25]:
# c. No AB != BA in this example.
# This tells us that the order in which you complete matrix multiplication operations matters since
# AB putting A first, B second does not yield the same result as B first A second.

In [ ]:
# Problem 3. Linear Transformations
#